name: "${project.name}"
main: "${project.groupId}.${project.artifactId}.${project.name}"
version: "${project.version}"
api-version: "${project.api-version}"
author: "${project.developers[0].name}"
description: "${project.description}"
depend: [ GriefPrevention ]
libraries:
  - it.unimi.dsi:fastutil:${fastutil.version}

commands:
  siege:
    aliases: [ gpsiege ]
    description: Main siege command
    permission: gpsiege.siege
